// Generated by LiveScript 1.2.0
(function(){
  chrome.extension.sendMessage({}, function(response){
    var readyStateCheckInterval;
    return readyStateCheckInterval = setInterval(function(){
      if (document.readyState === "complete") {
        clearInterval(readyStateCheckInterval);
        return console.log("Hello. This message was sent from scripts/inject.js");
      }
    }, 10);
  });
  chrome.runtime.onMessage.addListener(function(request, sender, sendResponse){
    if (request.hello === 'hi') {
      sendResponse({
        response: 'from_content_script'
      });
      return console.log('received');
    }
  });
}).call(this);
