// Generated by LiveScript 1.2.0
(function(){
  angular.module('ImageCrawlerApp', []).controller('PageController', function($scope){
    chrome.tabs.query({
      active: true,
      currentWindow: true
    }, function(tabs){
      return chrome.tabs.sendMessage(tabs[0].id, {
        hello: 'hi'
      }, function(response){
        console.log(tabs);
        return console.log(response.response);
      });
    });
    $scope.tab = 2;
    return $scope.selectImages = function(){
      return alert('message sent');
    };
  });
}).call(this);
