// Generated by LiveScript 1.2.0
(function(){
  angular.module('ImageCrawlerApp', []).controller('PageController', function($scope){
    return chrome.tabs.query({
      active: true,
      currentWindow: true
    }, function(tabs){
      var port;
      chrome.tabs.sendMessage(tabs[0].id, {
        hello: 'hi'
      }, function(response){
        console.log(tabs);
        return console.log(response.response);
      });
      port = chrome.tabs.connect(tabs[0].id, {
        name: 'imc_port'
      });
      $scope.tab = 2;
      return $scope.selectImages = function(){
        port.postMessage({
          hihi: 'long'
        });
        return port.onMessage.addListener(function(msg){
          alert(msg.res);
          return port.postMessage({
            res: 'from_popup'
          });
        });
      };
    });
  });
}).call(this);
